/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.productos.avro;
@org.apache.avro.specific.AvroGenerated
public enum CategoriaEnumAvro implements org.apache.avro.generic.GenericEnumSymbol<CategoriaEnumAvro> {
  GRANOS, LACTEOS, FRUTAS  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"CategoriaEnumAvro\",\"namespace\":\"org.productos.avro\",\"symbols\":[\"GRANOS\",\"LACTEOS\",\"FRUTAS\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
